/** Delivery cities — Maghreb wilayas by default; the field also accepts any city. */
export const CITIES = [
  "Alger",
  "Oran",
  "Constantine",
  "Annaba",
  "Blida",
  "Setif",
  "Batna",
  "Tlemcen",
  "Bejaia",
  "Tizi Ouzou",
  "Biskra",
  "Bechar",
  "Mostaganem",
  "Tiaret",
  "Ouargla",
  "Skikda",
  "Sidi Bel Abbes",
  "Jijel",
  "Tebessa",
  "El Oued",
  "Ghardaia",
  "Relizane",
  "Chlef",
  "Mascara",
  "Boumerdes",
  "Tipaza",
  "Ain Defla",
  "Medea",
  "Mila",
  "Guelma",
  "Khenchela",
  "Oum El Bouaghi",
  "Souk Ahras",
  "El Tarf",
  "Ain Temouchent",
  "Saida",
  "Tissemsilt",
  "Laghouat",
  "Djelfa",
  "Msila",
  "Bordj Bou Arreridj",
  "Bouira",
  "Adrar",
  "Tamanrasset",
  "Illizi",
  "Tindouf",
  "El Bayadh",
  "Naama",
  "Ouled Djellal",
  "El Mghair",
  "El Menia",
  "Timimoun",
  "Touggourt",
  "Djanet",
  "In Salah",
  "In Guezzam",
  "Beni Abbes",
] as const;
